-- Default development data loaded after Hibernate creates or updates the schema.

INSERT INTO COMPTE (EMAIL, PASSWORD_HASH, DATE_INSCRIPTION, NOM, PRENOM)
SELECT 'admin@univ-lyon1.fr', 'admin123', CURRENT_TIMESTAMP, 'Admin', 'UniFlow'
WHERE NOT EXISTS (SELECT 1 FROM COMPTE WHERE EMAIL = 'admin@univ-lyon1.fr');

INSERT INTO COMPTE_ROLES (COMPTE_ID, ROLES)
SELECT c.ID, 'ADMIN'
FROM COMPTE c
WHERE c.EMAIL = 'admin@univ-lyon1.fr'
  AND NOT EXISTS (
      SELECT 1 FROM COMPTE_ROLES cr
      WHERE cr.COMPTE_ID = c.ID AND cr.ROLES = 'ADMIN'
  );

INSERT INTO POLE (NAME)
SELECT 'Informatique'
WHERE NOT EXISTS (SELECT 1 FROM POLE WHERE NAME = 'Informatique');

INSERT INTO COMPTE (EMAIL, PASSWORD_HASH, DATE_INSCRIPTION, NOM, PRENOM)
SELECT 'organisateur@univ-lyon1.fr', 'org123', CURRENT_TIMESTAMP, 'Informatique', 'Organisateur'
WHERE NOT EXISTS (SELECT 1 FROM COMPTE WHERE EMAIL = 'organisateur@univ-lyon1.fr');

INSERT INTO COMPTE_ROLES (COMPTE_ID, ROLES)
SELECT c.ID, 'ORGANISATEUR'
FROM COMPTE c
WHERE c.EMAIL = 'organisateur@univ-lyon1.fr'
  AND NOT EXISTS (
      SELECT 1 FROM COMPTE_ROLES cr
      WHERE cr.COMPTE_ID = c.ID AND cr.ROLES = 'ORGANISATEUR'
  );

INSERT INTO ORGANISATION (NOM_STRUCTURE, POLE_ID)
SELECT 'Club Informatique', p.ID
FROM POLE p
WHERE p.NAME = 'Informatique'
  AND NOT EXISTS (
      SELECT 1 FROM ORGANISATION
      WHERE NOM_STRUCTURE = 'Club Informatique'
  );

INSERT INTO ORGANISATION_MEMBRES (ORGANISATION_ID, COMPTE_ID)
SELECT o.ID, c.ID
FROM ORGANISATION o, COMPTE c
WHERE o.NOM_STRUCTURE = 'Club Informatique'
  AND c.EMAIL = 'organisateur@univ-lyon1.fr'
  AND NOT EXISTS (
      SELECT 1 FROM ORGANISATION_MEMBRES om
      WHERE om.ORGANISATION_ID = o.ID AND om.COMPTE_ID = c.ID
  );
